<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <!-- Forked from oalt's MDD4All.UI.DataModels and renamed, so the two never meet in one build. Author and copyright stay his. -->
        <Version>2.0.0.0</Version>
        <Authors>MDD4All.de</Authors>
        <Company>MDD4All.de</Company>
        <Description>Data models for UI components</Description>
        <Copyright>© MDD4All.de</Copyright>
        <PackageReadmeFile>Nuget.md</PackageReadmeFile>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageTags>UI DataModels</PackageTags>
    </PropertyGroup>

    <PropertyGroup>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
    </ItemGroup>

    <ItemGroup>
        <None Include="Nuget.md">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
    </ItemGroup>

</Project>
